apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ndbf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wcmx-tenant/rhtap-demo-app/hacbs-test-project-ndbf@sha256:e620eec507b70d72490e4ccd1c388679dcaa8482eda37c0e2b3534e68f225645
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
